### ISSUE TITLE
Add preserveSvg argument to ImageObjectType.srcSet

### ISSUE THREAD

**Issue by mgax** [torchbox/wagtail-grapple#369]
The `preserveSvg` argument, introduced in https://github.com/torchbox/wagtail-grapple/commit/802428fd0e0e56be484a1f279917739a83cc435e on the `rendition` field, would also be super useful on the `srcSet` field, to avoid such errors when requesting `srcSet(sizes: [360, 1024], format: "webp")` on an SVG image:

> 'SvgImage' object has no attribute 'save_as_webp'

Ref: #359
